export const userData =[
    {
        id: '1',
        name: 'Miguel irmão',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '2',
        name: 'Mamãe',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '3',
        name: 'Papai',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '4',
        name: 'Agatha minha vida 💙💙',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '5',
        name: 'Isaquezin',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '6',
        name: 'Imagine Dragons',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '7',
        name: 'Nirvana',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '8',
        name: 'Billie Eillish',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '9',
        name: 'Khalid',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '10',
        name: 'Twenty one Pilots',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '11',
        name: 'Kemuel',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '12',
        name: 'Ed Sheeran',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '13',
        name: 'Harry Styles',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '14',
        name: 'Bruno Mars',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '15',
        name: 'Doja Cat',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '16',
        name: 'Lil Nas X',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '17',
        name: 'Ariana Grande',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '18',
        name: 'J balvin',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '19',
        name: 'Cardi B',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '20',
        name: 'The Weekend',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '21',
        name: 'Jack Harlow',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '22',
        name: 'Shawn Mendes',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '23',
        name: 'YOUNGBLUD',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '24',
        name: 'Machine Gun Kelly',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '25',
        name: 'Travis Scott',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '26',
        name: 'Kayne West',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '27',
        name: 'Recayd Mob',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '28',
        name: 'Jé Santiago',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '29',
        name: 'Sub Urban',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '30',
        name: 'Jaden Smith',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '31',
        name: 'Justin Bieber',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '32',
        name: 'The Kid LAROI',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '33',
        name: 'Eminem',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '34',
        name: 'Oliver Tree',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '35',
        name: 'Blackbear',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '36',
        name: 'Yunk Vino',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '37',
        name: 'Abbot',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '38',
        name: 'Playboi Carti',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '39',
        name: 'Trippie Redd',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '40',
        name: 'Surf Curse',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '41',
        name: 'AC/DC',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '42',
        name: 'The Beatles',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '43',
        name: 'Queen',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '44',
        name: 'Michael Jackson',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '45',
        name: 'Dua Lipa',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '46',
        name: 'Giveon',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '47',
        name: 'Daniel Caesar',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '48',
        name: 'Marshmello',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '49',
        name: 'Tyga',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '50',
        name: 'Elton Jhon',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '51',
        name: 'One Republic',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '52',
        name: 'Maroon 5',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '53',
        name: 'Bella Poarch',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '54',
        name: 'Post Malone',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '55',
        name: 'Nations Worship',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '56',
        name: 'Gold yt',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '57',
        name: 'Tai Verdes',
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '58',
        name: "Artic Monkey's",
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '59',
        name: "Gorillaz",
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
    {
        id: '60',
        name: "Bin",
        Galery: {
            photo1: '',
            photo2: '',
            photo3: '',
            photo4: '',
            photo5: '',
            photo6: '',
            photo7: '',
            photo8: '',
            photo9: '',
            photo10: '',
        }
    },
]